In [4]:
import numpy as np


In [ ]:
a = np.array([1,2,3,4,5])
a.shape
a.dtype



dtype('int64')

In [15]:
b=np.zeros((3,4))
print(b)

np.full((2, 2), 7)

np.arange(0, 10, 1) 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.randn(3, 3)     # standard normal (values lie between -3 and 3)
np.random.rand(3, 3)        # valeus between 0 and 1

array([[0.62275389, 0.61098866, 0.04241651],
       [0.74422091, 0.35258883, 0.14975283],
       [0.97401926, 0.2088227 , 0.3998617 ]])

In [ ]:
#Slicing, indexing
a[1:3]
a[a>2]


np.int64(6)

In [26]:

m = np.array([[1,2,3],[4,5,6]])
m[0, :]       # first row
m[:,1]

array([2, 5])

In [31]:
a = np.arange(12)
a.reshape(3, 4)
a.reshape(-1, 4)   # -1 means "infer this dimension"
a.flatten()  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
a = np.array([[1,2,3],[4,5,6]])   # shape (2,3)
b = np.array([10,20,30])          # shape (3,)
a + b

array([[11, 22, 33],
       [14, 25, 36]])

In [35]:

result = np.arange(1000000) ** 2
print(result)

[           0            1            4 ... 999994000009 999996000004
 999998000001]
